<a href="https://colab.research.google.com/github/acubillosunal/UBM-MACHINE-LEARNING-1/blob/main/05-%5BTaller%5D-numpy.ipynb#scrollTo=bm0ko4ipL_Ks" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Recuerda que una vez abierto, Da clic en "Copiar en Drive", de lo contrario no podras alamancenar tu progreso**

Nota: no olvide ir ejecutando las celdas de código de arriba hacia abajo para que no tenga errores de importación de librerías o por falta de definición de variables.

# **Taller Numpy**



1) Importar la libreria numpy y ver la versión que se está usando

In [2]:
import numpy as np
print("Versión de NumPy:", np.__version__)

Versión de NumPy: 1.23.5


2) Crear un arreglo de tamaño 1D desde 10 hasta 30

In [17]:
#Primera Opción
array = []
for i in range (10,31):
  array.append(i)
print(array)

#Segunda Opcion
array0 = np.arange(10, 31)
print(array0)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


3) Crear un arreglo booleano con valor True de tamaño 4x4

In [6]:
booleano = np.full((4, 4), True, dtype=bool)
print(booleano)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


4) Generar un arreglo desde el 10 hasta el 30, extraer los elementos pares del arreglo generado.

In [7]:
array1 = np.arange(10, 31)
pares = array1[array1 % 2 == 0]
print(pares)

[10 12 14 16 18 20 22 24 26 28 30]


5) Reemplazar todos los números pares por -1 de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando bucles y condicionales.

In [8]:
array2 = np.arange(10, 31)
cont = 0
for j in array2:
  if(j%2 == 0):
    array2[cont] = -1
  cont+=1
print(array2)

[-1 11 -1 13 -1 15 -1 17 -1 19 -1 21 -1 23 -1 25 -1 27 -1 29 -1]


6) Reemplazar todos los números pares por -1 de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando una función de numpy.

In [9]:
array3 = np.arange(10, 31)
mod = np.where(array3 % 2 == 0, -1, array3)
print(mod)

[-1 11 -1 13 -1 15 -1 17 -1 19 -1 21 -1 23 -1 25 -1 27 -1 29 -1]


7) Reemplazar todos los números pares por -1 y por 0 los impares de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando bucles y condicionales.

In [10]:
array4 = np.arange(10, 31)
cont = 0
for j in array4:
  if(j%2 == 0):
    array4[cont] = -1
  else:
    array4[cont] = 0
  cont+=1
print(array4)

[-1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1]


8) Reemplazar todos los números pares por -1 y los impares por 0 de una arreglo desde 10 hasta 30 sin que afecte los demás elementos del arreglo utilizando una función de numpy.

In [13]:
array5 = np.arange(10, 31)
mod1 = np.where(array5 % 2 == 0,-1, 0)
print(mod1)

[-1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1  0 -1]
